# Generated by Django 5.1.4 on 2024-12-14 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanatorium_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='fecha_fin',
            new_name='fecha',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='fecha_inicio',
        ),
        migrations.AddField(
            model_name='tarea',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='archivos_tareas/'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='horas_invertidas',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarea',
            name='titulo',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
