# Generated by Django 5.1.4 on 2024-12-17 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanatorium_app', '0002_rename_fecha_fin_tarea_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='orden',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Reporte',
        ),
    ]
