# Generated by Django 5.1.4 on 2024-12-19 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanatorium_app', '0003_tarea_orden_delete_reporte'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Metricas',
        ),
    ]
